name = "LemonCookiePack"
author = "vladislemon"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9867bf3b8f5bd03d0e09c49fc41d7be38cb8a37dde51ca6f79cda6c3c1d55582"

[versions]
forge = "40.1.54"
minecraft = "1.18.2"
