name = "LemonCookiePack"
author = "vladislemon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b70dd9ed28181528830b60558710487e56ec2fde0f93f254adcd9d83db29d7a2"

[versions]
forge = "40.1.54"
minecraft = "1.18.2"
