name = "MultiFruit"
author = "vladislemon"
version = "3.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56f15e5b8676c92ec86ec280d63f80e3811c854d0a60d0eb022e457800e19269"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
