name = "MultiFruit"
author = "vladislemon"
version = "3.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00b8b0fa9566c8dbd4e3d488431efcc4380dedf55edf3a967807efe472bb2f31"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
