name = "MultiFruit"
author = "vladislemon"
version = "2.0.0-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "150c29a72e128298eb4eba83d84b8a6c32262ddee598228cd9aa61927913dd96"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
