name = "MultiFruit"
author = "vladislemon"
version = "3.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5021763037363133ea98f6cc3361ad8df585c30d3edc2d3368956e35030e2ce6"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
