name = "MultiFruit"
author = "vladislemon"
version = "3.4.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc2fec9decc73303998bc8c71c9b0fe52ef67ca424b277a0174728b2df20cab6"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
