name = "MultiFruit"
author = "vladislemon"
version = "3.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32c43e8255bad52a7035de0d67dd3d5d71c24ffa19f676643cca290c013c1d75"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
