name = "MultiFruit"
author = "vladislemon"
version = "2.0.0-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97c4b562c00d1619ba7b83229eae1c793d0b724837c55a5b8a0d3f8360e7762d"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
