name = "MultiFruit"
author = "vladislemon"
version = "3.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ec6794b01cab2237f85c8ce35170bba39c6212bb0adf72812f6a40e27a95e66"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
