name = "MultiFruit"
author = "vladislemon"
version = "3.1.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8583c5360f14d1598ad011c402ec6fd215428bba14868f90285ae85f65afc20"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
