name = "MultiFruit"
author = "vladislemon"
version = "3.1.20"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b74e9752d5f2b561a99cf51d16cb3699833a204aebe31e29fb3879abef8a57b0"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
