name = "MultiFruit"
author = "vladislemon"
version = "3.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29a35d123c5db13cec737e4dfa33b9b746bbbc06c3be198f44287f4580adf0af"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
