name = "MultiFruit"
author = "vladislemon"
version = "3.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef480bad7e4cbea8d5b6d843a3cfdea0bd548ad70aa6a02ff710c3cf846a99a9"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
