name = "MultiFruit"
author = "vladislemon"
version = "3.1.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "581a5b20bf5a90686c70fa88b6827c1bf4379205e6c03befa54a569855bc497a"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
