name = "MultiFruit"
author = "vladislemon"
version = "3.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f7e4f9315383938f690d972b3ed65e3ed974fd52d6f0f92f2afa4e482b5335d"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
