name = "MultiFruit"
author = "vladislemon"
version = "3.1.15"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1ea7f0924892f3e3dfdada5317a4c13cdd554aca4563a035c7b55b938fdf267"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
