name = "MultiFruit"
author = "vladislemon"
version = "3.1.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16bacc8acba1e677555898a6f4b9cd9cfb25a5309fcb0eea76203f03b161f886"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
