name = "MultiFruit"
author = "vladislemon"
version = "3.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c31306bd1a25875bede8575a625ab2ca2e12fe59a65520faf6d7eabad8bf3f84"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
