name = "MultiFruit"
author = "vladislemon"
version = "3.1.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17eb94ba7c6b3d9fc21e88dba339cb06f14b985c2d4bcba0a44650ac7ef11fdf"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
