name = "MultiFruit"
author = "vladislemon"
version = "2.0.0-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "241149fa96c91b7c132a308ee9895090232b5707c2bbcbcd3e981ba1a326d911"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
