name = "MultiFruit"
author = "vladislemon"
version = "3.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1b21ecb3dfcaee4ecc64d3e157d991adb2507f42f816eaaffb16535c62caf11"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
