name = "MultiFruit"
author = "vladislemon"
version = "3.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dcfec86603a5150ba96391674dafc4779f424d4edabf29ac4487306b9fc13361"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
