name = "MultiFruit"
author = "vladislemon"
version = "3.1.17"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2dbadbc67ebd6a40fbba244446e7dc33f1f66450ec2ea2b738696c278c0e16d"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
