name = "MultiFruit"
author = "vladislemon"
version = "3.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7af7607daba339c315fcd1c42c2f89238aeff5b139fbbf1321bf2a06e308f99"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
