name = "MultiFruit"
author = "vladislemon"
version = "3.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fbda3fec5cbe86787211e14008546beca93e75a5fb2ccac4eade324b5930465b"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
