name = "MultiFruit"
author = "vladislemon"
version = "3.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a45a235dfee772f2468104a4bb01b533faedadb995b678e6177dbf7cc8987faa"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
