name = "MultiFruit"
author = "vladislemon"
version = "3.1.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "acfc26c8a40c0d6e6e06f3331e91f31caa451b04b3ba5fd730021c6bbea0eb17"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
