name = "MultiFruit"
author = "vladislemon"
version = "3.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0177999b0536b2efd69305dbec5893a4933bdb0a5113261873d7c6ebc196b51"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
