name = "MultiFruit"
author = "vladislemon"
version = "3.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c14c9a3f64cf30bf0eaaae0d66a159b48b9b73e5ab9a26931dddfac54d0066fd"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
