name = "FTB Infinity Evolved"
author = "FTB Team (vladislemon edition)"
version = "3.2.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0adefbb1497d3a7051aed29475d8d4a14e0ad8b22539b3afd127883ff768c609"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
