name = "FTB Infinity Evolved"
author = "FTB Team (vladislemon edition)"
version = "3.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fdfdbc358739d01703a69f01dcd169a353f17455794f6e3ae1dff6c83def7711"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
