name = "FTB Infinity Evolved"
author = "FTB Team (vladislemon edition)"
version = "3.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f642ad9c83a1215090035c90070adba8c6c35e18130021435a5226826c7799df"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
