name = "Lite Pack Server"
author = "vladislemon"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16bdd133ff29bd115b9b0fa13e7175ba64666f96d3ce592d0f6d8c3f00053a55"

[versions]
forge = "40.1.86"
minecraft = "1.18.2"
