mods.immersiveengineering.Excavator.removeMineral("Bauxite");
mods.immersiveengineering.Excavator.removeMineral("Cassiterite");
mods.immersiveengineering.Excavator.removeMineral("Coal");
mods.immersiveengineering.Excavator.removeMineral("Copper");
mods.immersiveengineering.Excavator.removeMineral("Galena");
mods.immersiveengineering.Excavator.removeMineral("Gold");
mods.immersiveengineering.Excavator.removeMineral("Iron");
mods.immersiveengineering.Excavator.removeMineral("Lapis");
mods.immersiveengineering.Excavator.removeMineral("Lead");
mods.immersiveengineering.Excavator.removeMineral("Magnetite");
mods.immersiveengineering.Excavator.removeMineral("Nickel");
mods.immersiveengineering.Excavator.removeMineral("Platinum");
mods.immersiveengineering.Excavator.removeMineral("Pyrite");
mods.immersiveengineering.Excavator.removeMineral("Quartzite");
mods.immersiveengineering.Excavator.removeMineral("Silver");
mods.immersiveengineering.Excavator.removeMineral("Uranium");

mods.immersiveengineering.Excavator.addMineral("Aluminum", 15, 0.25, ["oreAluminum", "oreRuby", "oreSapphire"], [0.7, 0.15, 0.15], [-1, 1], true);
mods.immersiveengineering.Excavator.addMineral("Apatite", 30, 0.1, ["oreApatite", "oreSalt"], [0.8, 0.2], [-1, 1], true);
mods.immersiveengineering.Excavator.addMineral("Bauxite", 20, 0.2, ["oreAluminum", "oreTitanium"], [0.9, 0.1], [-1, 1], true);
mods.immersiveengineering.Excavator.addMineral("Cassiterite", 15, 0.2, ["oreTin", "oreElectrotine"], [0.85, 0.15], [-1, 1], true);
mods.immersiveengineering.Excavator.addMineral("Coal", 25, 0.1, ["oreCoal", "denseoreCoal", "oreDiamond", "oreEmerald"], [0.92, 0.1, 0.015, 0.015], [-1, 1], true);
mods.immersiveengineering.Excavator.addMineral("Copper", 30, 0.2, ["oreCopper", "oreGold", "oreNickel"], [0.65, 0.25, 0.05], [-1, 1], true);
mods.immersiveengineering.Excavator.addMineral("Galena", 15, 0.2, ["oreLead", "oreSilver", "oreSulfur"], [0.4, 0.4, 0.1], [-1, 1], true);
mods.immersiveengineering.Excavator.addMineral("Glowerite", 5, 0.2, ["glowstone", "oreQuartz"], [0.69, 0.31], [-1], false);
mods.immersiveengineering.Excavator.addMineral("Gold", 20, 0.3, ["oreGold", "oreCopper", "oreNickel"], [0.65, 0.25, 0.05], [-1, 1], true);
mods.immersiveengineering.Excavator.addMineral("Iron", 25, 0.1, ["oreIron", "oreNickel", "oreTin", "orePeridot"], [0.5, 0.25, 0.2, 0.1], [-1, 1], true);
mods.immersiveengineering.Excavator.addMineral("Lapis", 10, 0.2, ["oreLapis", "oreIron", "oreSulfur"], [0.65, 0.275, 0.025], [-1, 1], true);
mods.immersiveengineering.Excavator.addMineral("Lead", 10, 0.15, ["oreLead", "oreSilver"], [0.55, 0.4], [-1, 1], true);
mods.immersiveengineering.Excavator.addMineral("Magnetite", 25, 0.1, ["oreIron", "oreGold", "oreRedstone"], [0.85, 0.15, 0.1], [-1, 1], true);
mods.immersiveengineering.Excavator.addMineral("Netherite", 15, 0.2, ["oreQuartz", "glowstone"], [0.84, 0.16], [-1], false);
mods.immersiveengineering.Excavator.addMineral("Nickel", 20, 0.3, ["oreNickel", "orePlatinum", "oreIron"], [0.85, 0.05, 0.05], [-1, 1], true);
mods.immersiveengineering.Excavator.addMineral("Platinum", 5, 0.35, ["orePlatinum", "oreNickel"], [0.4, 0.3], [-1, 1], true);
mods.immersiveengineering.Excavator.addMineral("Pyrite", 20, 0.1, ["oreIron", "oreSulfur"], [0.5, 0.5], [-1, 1], true);
mods.immersiveengineering.Excavator.addMineral("Quartzite", 5, 0.3, ["oreCertusQuartz", "oreChargedCertusQuartz"], [0.896, 0.104], [-1, 1], true);
mods.immersiveengineering.Excavator.addMineral("Redstone", 15, 0.2, ["oreRedstone", "oreGold"], [0.85, 0.15], [-1, 1], true);
mods.immersiveengineering.Excavator.addMineral("Silver", 10, 0.2, ["oreSilver", "oreLead"], [0.55, 0.4], [-1, 1], true);
mods.immersiveengineering.Excavator.addMineral("Sphalerite", 15, 0.2, ["oreZinc", "oreIron"], [0.8, 0.2], [-1, 1], true);
mods.immersiveengineering.Excavator.addMineral("Uranium", 10, 0.35, ["oreUranium", "oreLead"], [0.55, 0.3], [-1, 1], true);
mods.immersiveengineering.Excavator.addMineral("Wolframite", 10, 0.35, ["oreTungsten", "oreIron"], [0.55, 0.45], [-1, 1], true);
