name = "LemonCookiePack"
author = "vladislemon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e074837947dd7054624acfb63ff6d2974308df5df4abad7d1893ddc3b7d1d890"

[versions]
forge = "40.1.54"
minecraft = "1.18.2"
