name = "LemonCookiePack"
author = "vladislemon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c86193c09f743fb22285abf887db776bd0005df803c39f4486bba023fbd113f9"

[versions]
forge = "40.1.54"
minecraft = "1.18.2"
