name = "LemonCookiePack"
author = "vladislemon"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9a74aa6bebfb77ec9642dba33390ad10804288f4faae57ac74ac4e498372dfb"

[versions]
forge = "40.1.68"
minecraft = "1.18.2"
