name = "LemonCookiePack"
author = "vladislemon"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60caa13d0ca78c2683c344e27c32084930eb7e7019737075562d66981d32127e"

[versions]
forge = "40.1.54"
minecraft = "1.18.2"
