name = "LemonCookiePack"
author = "vladislemon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b576153dbec3cfb22e23f715a92bb31a4929709ba3401a3b27deda9217bb84dd"

[versions]
forge = "40.1.54"
minecraft = "1.18.2"
