name = "LemonCookiePack"
author = "vladislemon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "294f33b5272a11fbcb0355f60db4c95be783e86d7c897fcb8859c56512869496"

[versions]
forge = "40.1.54"
minecraft = "1.18.2"
