name = "LemonCookiePack"
author = "vladislemon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0415764234f7b4b2860ef1696f8777e4d2f4b092c0356004e37c9b069be35189"

[versions]
forge = "40.1.54"
minecraft = "1.18.2"
