name = "LemonCookiePack"
author = "vladislemon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2fd29a337bacadfafa72f2b7f8c19822640b60c0a7b28e14947d19c06291268"

[versions]
forge = "40.1.54"
minecraft = "1.18.2"
